### PR TITLE
Fix pointLight cords

### PR DESCRIPTION
**Pull request by Kobreros**
"three": "^0.165.0"
I don't know why, but the model only shows up if I add these arguments.

### CODE REVIEW

**Comment by AndrewSink** [comment]
Interesting! Can you upload the model you're having trouble with? I've tested with several  .STL files, and haven't had this issue. 

Can you try uploading this model and seeing if it works for you?

https://www.thingiverse.com/thing:138642

**Comment by Kobreros** [comment]
This is not specific to a certain model, this problem occurs with any. I have attached a video with an example of what it looks like for me.

https://github.com/AndrewSink/STL-to-ASCII-Generator/assets/15179643/52ff76b2-8cb2-4961-a4e9-0482d2c21b8d

**Comment by elvisdragonmao** [comment]
I had the same issue! Adding `, 0, 0);` fixed it. Thanks, @Kobreros.  
@AndrewSink, I'm using the default model and encountered the same problem. It could be related to a three.js update. Could you consider uploading `package.json`?

**Comment by elvisdragonmao** [comment]
By the way, this is cute uwu
```js
var userUploaded = false;
if (userUploaded == false) {
  userUploaded = true;
}
```

**Pull request merged**
